// ============================================================
// GAMEPLAY SEED DATA — Moved from config/index.ts
// ============================================================

// ============================================================
// 10 THẬP TUYỆT THỂ — Body Constitution Seed Data
// Nguồn: Truyện Cổ Chân Nhân (Reverend Insanity)
// Mỗi Thể tương đương 1 "hệ" nhân vật, với passive và stat riêng
// ============================================================
export const bodyConstitutionSeeds = [
  {
    id: 1,
    name: 'Xuân Thu Cốc Thần Thể',
    description:
      'Thể mạnh nhất trong Thập Tuyệt Thể. Người sở hữu mang sức mạnh nguyên thuỷ của đất trời, tinh khí sung mãn vô cùng, thọ mạng dài đặng gần như bất tử.',
    stat_bonuses: JSON.stringify({ hp_pct: 50, mana_pct: 30, def_pct: 20 }),
    passive_ability: 'immortal_vitality',
    passive_description:
      'Hồi phục 2% HP tối đa mỗi 5 giây. Miễn dịch 30% sát thương từ độc và lửa.',
    realm_scaling: true,
    rarity: 'legendary',
  },
  {
    id: 2,
    name: 'Hồng Nhan Lâu Thể',
    description:
      'Xuất hiện trong nữ tu sĩ tài hoa. Vẻ ngoài mê hoặc thiên hạ, tâm tính đặc biệt nhạy cảm với cảm xúc. Có thể tác động tâm thần kẻ địch trong chiến đấu.',
    stat_bonuses: JSON.stringify({ mana_pct: 40, spd_pct: 20, atk_pct: 10 }),
    passive_ability: 'charm_aura',
    passive_description:
      'Khi tấn công, có 15% cơ hội khiến kẻ địch mất 1 lượt (bị mê hoặc). Tăng 20% hiệu quả kỹ năng hỗ trợ.',
    realm_scaling: true,
    rarity: 'legendary',
  },
  {
    id: 3,
    name: 'Ám Kim Quỷ Thể',
    description:
      'Thể tối thượng của hệ Kim, da thịt cứng như kim cương, sức công phá vô song. Người sở hữu thiên về tấn công trực diện và phá giáp.',
    stat_bonuses: JSON.stringify({ atk_pct: 40, def_pct: 30, hp_pct: 10 }),
    passive_ability: 'iron_skin',
    passive_description:
      'Mỗi đòn tấn công bỏ qua 20% giáp của kẻ địch. Nhận 15% ít sát thương vật lý hơn.',
    realm_scaling: true,
    rarity: 'legendary',
  },
  {
    id: 4,
    name: 'Huyết Hải Cổ Thể',
    description:
      'Thể cực hiếm liên quan đến huyết mạch cổ xưa. Máu của người sở hữu mang độc tính và tái sinh mãnh liệt, mỗi lần bị thương lại trở nên hung hãn hơn.',
    stat_bonuses: JSON.stringify({ hp_pct: 60, atk_pct: 20 }),
    passive_ability: 'blood_frenzy',
    passive_description:
      'Khi HP dưới 50%, tăng 25% ATK. Khi HP dưới 25%, tăng thêm 25% ATK (cộng dồn). Hồi 1% HP khi tiêu diệt kẻ địch.',
    realm_scaling: true,
    rarity: 'legendary',
  },
  {
    id: 5,
    name: 'Phong Vân Thiên Thể',
    description:
      'Thể của gió và mây, thân pháp tuyệt đỉnh. Người sở hữu di chuyển nhanh như gió, khó bị tấn công và xuất chiêu liên hoàn.',
    stat_bonuses: JSON.stringify({ spd_pct: 60, mana_pct: 20, atk_pct: 10 }),
    passive_ability: 'wind_step',
    passive_description:
      'Tăng 30% tốc độ di chuyển. Có 20% cơ hội né tránh hoàn toàn đòn tấn công. Cooldown kỹ năng giảm 15%.',
    realm_scaling: true,
    rarity: 'legendary',
  },
  {
    id: 6,
    name: 'Linh Thể Đoán Mệnh',
    description:
      'Thể liên kết với thiên mệnh, người sở hữu có trực giác siêu nhiên, có thể dự cảm hiểm nguy và nắm bắt thời cơ tấn công hoàn hảo.',
    stat_bonuses: JSON.stringify({ atk_pct: 25, mana_pct: 25, spd_pct: 15 }),
    passive_ability: 'fate_sense',
    passive_description:
      'Đòn đánh đầu tiên vào kẻ địch trong mỗi trận luôn là chí mạng. Tăng 30% tỉ lệ chí mạng sau đó.',
    realm_scaling: false,
    rarity: 'epic',
  },
  {
    id: 7,
    name: 'Vạn Độc Bất Xâm Thể',
    description:
      'Thể miễn dịch bách độc, cơ thể tiêu hoá và biến mọi loại độc thành dưỡng chất. Chiến đấu lâu dài người sở hữu ngày càng mạnh hơn.',
    stat_bonuses: JSON.stringify({ hp_pct: 30, def_pct: 30, mana_pct: 10 }),
    passive_ability: 'poison_immune',
    passive_description:
      'Hoàn toàn miễn dịch mọi hiệu ứng độc. Khi bị tấn công bằng độc, hấp thụ và hồi 5% HP. Khi chiến đấu liên tục trên 30 giây, DEF tăng 20%.',
    realm_scaling: false,
    rarity: 'epic',
  },
  {
    id: 8,
    name: 'Băng Tâm Ngọc Thể',
    description:
      'Thể thuần khiết của hệ Băng, tâm trí lạnh lẽo như băng tuyết. Người sở hữu không bao giờ hoảng loạn, kỹ năng băng mạnh gấp bội.',
    stat_bonuses: JSON.stringify({ mana_pct: 50, def_pct: 20, hp_pct: 10 }),
    passive_ability: 'frozen_mind',
    passive_description:
      'Miễn dịch hiệu ứng Sợ Hãi và Hỗn Loạn. Kỹ năng băng tăng 40% sát thương. Có 10% cơ hội đóng băng kẻ địch khi bị tấn công.',
    realm_scaling: false,
    rarity: 'epic',
  },
  {
    id: 9,
    name: 'Lôi Hỏa Thần Thể',
    description:
      'Thể song hành giữa sét và lửa, sức công phá mạnh mẽ nhất trong các Thể tấn công. Người sở hữu thiên về lối đánh bùng nổ, sát thương diện rộng.',
    stat_bonuses: JSON.stringify({ atk_pct: 45, mana_pct: 15, spd_pct: 10 }),
    passive_ability: 'thunder_flame',
    passive_description:
      'Tăng 35% sát thương kỹ năng. Kỹ năng tấn công có thêm hiệu ứng đốt cháy (burn 3% HP/giây trong 3 giây). Khi HP đầy, đòn đánh đầu tiên gây thêm 50% sát thương.',
    realm_scaling: false,
    rarity: 'epic',
  },
  {
    id: 10,
    name: 'Hư Không Hóa Thần Thể',
    description:
      'Thể bí ẩn nhất, liên kết với cõi hư không. Người sở hữu có thể thoát khỏi không gian thực tại trong tích tắc, né tránh siêu phàm và tấn công từ hư vô.',
    stat_bonuses: JSON.stringify({ spd_pct: 30, mana_pct: 30, atk_pct: 20 }),
    passive_ability: 'void_step',
    passive_description:
      'Mỗi 20 giây, tự động kích hoạt né tránh hoàn toàn 1 đòn tấn công. Tăng 25% sát thương khi tấn công từ phía sau kẻ địch.',
    realm_scaling: true,
    rarity: 'legendary',
  },
];

export const npcSeeds = [
  {
    name: 'Trưởng làng',
    sprite: 'char_2',
    faction: 'chinh_dao',
    occupation: 'village_chief',
    mapId: 'bac_nguyen',
    x: 500,
    y: 400,
  },
  {
    name: 'Thợ rèn',
    sprite: 'char_3',
    faction: 'neutral',
    occupation: 'blacksmith',
    mapId: 'bac_nguyen',
    x: 600,
    y: 300,
    hasShop: 'true',
  },
  {
    name: 'Thương nhân',
    sprite: 'char_4',
    faction: 'neutral',
    occupation: 'merchant',
    mapId: 'bac_nguyen',
    x: 400,
    y: 500,
    hasShop: 'true',
  },
  {
    name: 'Trưởng lão',
    sprite: 'char_5',
    faction: 'chinh_dao',
    occupation: 'elder',
    mapId: 'bac_nguyen',
    x: 700,
    y: 450,
  },
  {
    name: 'Bia Đá Cổ',
    sprite: 'char_5',
    faction: 'neutral',
    occupation: 'lore_stele',
    mapId: 'rung_tuyet',
    x: 1000,
    y: 800,
  },
  {
    name: 'Bạch Lang Vương',
    sprite: 'boss_wolf_king',
    faction: 'ma_dao',
    occupation: 'story_boss',
    mapId: 'dinh_bangphong',
    x: 1000,
    y: 450,
  },
];

export const questSeeds = [
  {
    name: 'Lời chào từ trưởng làng',
    type: 'main',
    description: 'Hãy đến gặp Trưởng làng và lắng nghe lời khuyên đầu tiên của người.',
    npcGiverId: null,
    objectives: JSON.stringify([{ type: 'talk', target: 'Trưởng làng', count: 1, description: 'Nói chuyện with Trưởng làng' }]),
    rewards: JSON.stringify([{ type: 'gold', amount: 50 }, { type: 'exp', amount: 20 }]),
    flagComplete: 'talked_village_chief',
  },
  {
    name: 'Dọn dẹp quái vật',
    type: 'side',
    description: 'Những con quái vật đang quấy phá khu rừng gần làng. Hãy tiêu diệt 3 con.',
    npcGiverId: null,
    objectives: JSON.stringify([{ type: 'kill', target: 'wild_beast', count: 3, description: 'Tiêu diệt 3 Quái Thú Hoang Dã' }]),
    rewards: JSON.stringify([{ type: 'gold', amount: 100 }, { type: 'exp', amount: 50 }, { type: 'spirit_stone', amount: 5 }]),
  },
];

export const itemSeeds = [
  { name: 'Bình Hồi Máu Nhỏ', type: 'consumable', description: 'Hồi phục 50 HP', stackable: 'true', maxStack: 99, sellPrice: 10, sprite: 'gui_icon_potion' },
  { name: 'Bình Hồi Mana Nhỏ', type: 'consumable', description: 'Hồi phục 30 Mana', stackable: 'true', maxStack: 99, sellPrice: 10, sprite: 'gui_icon_potion' },
  { name: 'Đá Linh Hồn', type: 'material', description: 'Nguyên liệu luyện khí cơ bản', stackable: 'true', maxStack: 999, sellPrice: 5, sprite: 'gui_icon_gem' },
  { name: 'Lông Thú', type: 'quest_item', description: 'Lông của Quái Thú Hoang Dã', stackable: 'true', maxStack: 99, sellPrice: 2, sprite: 'gui_icon_feather' },
  { name: 'Thảo Dược', type: 'material', description: 'Thảo dược quý của Bắc Nguyên', stackable: 'true', maxStack: 99, sellPrice: 3, sprite: 'gui_icon_herb' },
  { name: 'Mảnh Bản Đồ', type: 'quest_item', description: 'Bản đồ cổ chỉ dẫn lên núi', stackable: 'false', maxStack: 1, sellPrice: 0, sprite: 'gui_icon_map' },
  { name: 'Kiếm Băng Hàn', type: 'weapon', description: 'Thanh kiếm mang luồng hàn khí thấu xương', stackable: 'false', maxStack: 1, sellPrice: 100, sprite: 'eq_vu_khi_h' },
  { name: 'Tinh Hoa Băng', type: 'quest_item', description: 'Tinh hoa kết tụ của Bạch Lang Vương', stackable: 'false', maxStack: 1, sellPrice: 0, sprite: 'gui_icon_essence' },
  { name: 'Mật Gấu', type: 'quest_item', description: 'Mật của Thiết Bì Cự Hùng', stackable: 'false', maxStack: 1, sellPrice: 0, sprite: 'gui_icon_gall' },
];

export const monsterSeeds = [
  {
    name: 'Quái Thú Hoang Dã',
    realm: 'pham_nhan',
    hp: 45,
    atk: 8,
    def: 2,
    speed: 3,
    element: 'physical',
    sprite: 'mob_beast',
    drop_table: JSON.stringify([
      { itemName: 'Lông Thú', chance: 0.6, minQuantity: 1, maxQuantity: 3 },
      { itemName: 'Đá Linh Hồn', chance: 0.15, minQuantity: 1, maxQuantity: 2 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 60,  // 60s — weak mob
  },
  {
    name: 'Sói Bắc Nguyên',
    realm: 'pham_nhan',
    hp: 70,
    atk: 12,
    def: 4,
    speed: 5,
    element: 'physical',
    sprite: 'mob_wolf',
    drop_table: JSON.stringify([
      { itemName: 'Lông Thú', chance: 0.7, minQuantity: 2, maxQuantity: 4 },
      { itemName: 'Đá Linh Hồn', chance: 0.2, minQuantity: 2, maxQuantity: 5 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 90,  // 90s — normal mob
  },
  {
    name: 'Hỏa Hồ Yêu',
    realm: 'luyen_khi',
    hp: 130,
    atk: 18,
    def: 8,
    speed: 6,
    element: 'fire',
    sprite: 'mob_fox',
    drop_table: JSON.stringify([
      { itemName: 'Đá Linh Hồn', chance: 0.4, minQuantity: 3, maxQuantity: 8 },
      { itemName: 'Bình Hồi Máu Nhỏ', chance: 0.1, minQuantity: 1, maxQuantity: 1 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 120,  // 2 min — stronger mob
  },
  {
    name: 'Thiết Bì Cự Hùng',
    realm: 'luyen_khi',
    hp: 250,
    atk: 22,
    def: 12,
    speed: 4,
    element: 'earth',
    sprite: 'mob_bear',
    drop_table: JSON.stringify([
      { itemName: 'Đá Linh Hồn', chance: 0.8, minQuantity: 5, maxQuantity: 10 },
      { itemName: 'Mật Gấu', chance: 1.0, minQuantity: 1, maxQuantity: 1 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 180,  // 3 min — elite mob
  },
];

export const guSeeds = [
  {
    template: {
      name: 'Hỏa Cổ',
      rank: 1,
      element: 'Fire',
      role: 'damage',
      quality: 'common',
      description: 'Cổ Trùng hệ Hỏa phổ biến. Tăng sát thương hỏa và thiêu đốt kẻ địch.',
      sprite: 'gu_fire',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 25, def: 0, crit: 5, crit_damage: 10, move_speed: 0, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'fire_blast',
        name: 'Hỏa Cầu',
        type: 'active',
        description: 'Bắn một quả cầu lửa về phía kẻ địch, gây sát thương Hỏa.',
        cooldown: 3,
        damage_multiplier: 150,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Phong Cổ',
      rank: 1,
      element: 'Wind',
      role: 'support',
      quality: 'common',
      description: 'Cổ Trùng hệ Phong. Tăng tốc độ di chuyển và tốc đánh.',
      sprite: 'gu_wind',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 5, def: 0, crit: 0, crit_damage: 0, move_speed: 10, attack_speed: 8, life_steal: 0 },
    skills: [
      {
        skill_id: 'wind_step',
        name: 'Phong Bộ',
        type: 'passive',
        description: 'Tăng tốc độ di chuyển.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Thạch Cổ',
      rank: 1,
      element: 'Earth',
      role: 'tank',
      quality: 'common',
      description: 'Cổ Trùng hệ Thổ. Tăng phòng thủ và máu tối đa.',
      sprite: 'gu_stone',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 150, atk: 0, def: 20, crit: 0, crit_damage: 0, move_speed: 0, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'stone_armor',
        name: 'Thạch Giáp',
        type: 'passive',
        description: 'Tăng phòng thủ.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Huyết Cổ',
      rank: 1,
      element: 'Blood',
      role: 'utility',
      quality: 'common',
      description: 'Cổ Trùng hệ Huyết. Hút máu từ kẻ địch, hồi phục bản thân.',
      sprite: 'gu_blood',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 50, atk: 10, def: 5, crit: 0, crit_damage: 0, move_speed: 0, attack_speed: 0, life_steal: 5 },
    skills: [
      {
        skill_id: 'blood_drain',
        name: 'Hấp Huyết',
        type: 'active',
        description: 'Hút máu từ kẻ địch, hồi 50% sát thương gây ra.',
        cooldown: 6,
        damage_multiplier: 120,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Độc Cổ',
      rank: 1,
      element: 'Poison',
      role: 'control',
      quality: 'common',
      description: 'Cổ Trùng hệ Độc. Gây độc lên kẻ địch, giảm tốc và sát thương theo thời gian.',
      sprite: 'gu_poison',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 15, def: 0, crit: 3, crit_damage: 0, move_speed: 0, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'poison_sting',
        name: 'Độc Châm',
        type: 'active',
        description: 'Tiêm độc vào kẻ địch, gây sát thương độc trong 5 giây.',
        cooldown: 4,
        damage_multiplier: 100,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Nguyệt Quang Cổ',
      rank: 1,
      element: 'light',
      role: 'damage',
      quality: 'common',
      description: 'Cổ trùng đặc trưng của Cổ Nguyệt gia tộc, ngưng tụ nguyệt nhận màu xanh nhạt cắt đứt đối thủ.',
      sprite: 'gu_moonlight',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 35, def: 0, crit: 8, crit_damage: 15, move_speed: 0, attack_speed: 5, life_steal: 0 },
    skills: [
      {
        skill_id: 'moon_blade',
        name: 'Nguyệt Nhận',
        type: 'active',
        description: 'Phóng ra một lưỡi đao trăng khuyết bán nguyệt.',
        cooldown: 2,
        damage_multiplier: 130,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Hùng Lực Cổ',
      rank: 1,
      element: 'physical',
      role: 'damage',
      quality: 'common',
      description: 'Tăng vĩnh viễn sức mạnh của một con gấu đen cho cơ thể.',
      sprite: 'gu_bear',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 80, atk: 30, def: 5, crit: 2, crit_damage: 5, move_speed: -5, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'bear_strength',
        name: 'Hùng Chi Cự Lực',
        type: 'passive',
        description: 'Gia tăng sát thương vật lý đáng kể.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Thiết Bì Cổ',
      rank: 1,
      element: 'earth',
      role: 'tank',
      quality: 'common',
      description: 'Khiến da dẻ trở nên thô ráp như sắt thép chịu đựng sát thương tốt.',
      sprite: 'gu_ironskin',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 120, atk: 0, def: 25, crit: 0, crit_damage: 0, move_speed: -8, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'iron_skin',
        name: 'Thiết Giáp Thân',
        type: 'passive',
        description: 'Tự động giảm lượng sát thương nhận vào.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Ngọc Cốt Cổ',
      rank: 2,
      element: 'earth',
      role: 'tank',
      quality: 'rare',
      description: 'Biến xương cốt thành ngọc thạch trắng muốt, cứng cáp bất phàm.',
      sprite: 'gu_jadebone',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 200, atk: 0, def: 45, crit: 0, crit_damage: 0, move_speed: 0, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'jade_bone',
        name: 'Ngọc Cốt Bảo Vệ',
        type: 'passive',
        description: 'Xương ngọc cứng cáp phản chấn 10% sát thương nhận vào.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Kiếm Khí Cổ',
      rank: 2,
      element: 'physical',
      role: 'damage',
      quality: 'rare',
      description: 'Luyện chế từ kiếm ý thô sơ, bắn ra những tia kiếm khí sắc bén cự ly trung.',
      sprite: 'gu_swordqi',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 55, def: 0, crit: 10, crit_damage: 25, move_speed: 5, attack_speed: 5, life_steal: 0 },
    skills: [
      {
        skill_id: 'sword_blast',
        name: 'Kiếm Khí Phóng Ra',
        type: 'active',
        description: 'Phóng luồng kiếm khí thẳng về phía trước càn quét kẻ địch.',
        cooldown: 4,
        damage_multiplier: 180,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Băng Trầm Cổ',
      rank: 2,
      element: 'ice',
      role: 'control',
      quality: 'rare',
      description: 'Trầm tích hàn băng ngàn năm, tỏa ra khí tức đóng băng làm chậm chuyển động kẻ thù.',
      sprite: 'gu_frost',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 100, atk: 25, def: 15, crit: 5, crit_damage: 10, move_speed: 0, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'frost_bite',
        name: 'Băng Hàn Châm',
        type: 'active',
        description: 'Phóng ra vụn băng làm chậm đối thủ 30% trong 3 giây.',
        cooldown: 5,
        damage_multiplier: 120,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Hóa Cam Cổ',
      rank: 2,
      element: 'wood',
      role: 'support',
      quality: 'common',
      description: 'Cổ trùng hỗ trợ trị liệu, biến hóa chướng khí thành mật ngọt cam lộ để dưỡng thương.',
      sprite: 'gu_nectar',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 150, atk: 0, def: 10, crit: 0, crit_damage: 0, move_speed: 10, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'sweet_nectar',
        name: 'Cam Lộ Thuật',
        type: 'active',
        description: 'Hồi phục một lượng sinh mệnh lập tức.',
        cooldown: 8,
        damage_multiplier: 80,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Tử Điện Cổ',
      rank: 3,
      element: 'lightning',
      role: 'damage',
      quality: 'rare',
      description: 'Tụ tập sấm chớp tím, giật điện cực mạnh khi đánh trúng mục tiêu.',
      sprite: 'gu_lightning',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 80, def: 0, crit: 15, crit_damage: 30, move_speed: 15, attack_speed: 10, life_steal: 0 },
    skills: [
      {
        skill_id: 'purple_lightning',
        name: 'Tử Điện Lôi Kích',
        type: 'active',
        description: 'Gọi một tia sét tím đánh trúng mục tiêu và gây tê liệt nhẹ.',
        cooldown: 4,
        damage_multiplier: 210,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Thanh Đồng Y Cổ',
      rank: 3,
      element: 'earth',
      role: 'tank',
      quality: 'rare',
      description: 'Bọc một lớp giáp màu đồng xanh lá bao phủ toàn thân tăng phòng ngự đáng kinh ngạc.',
      sprite: 'gu_bronzeskin',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 350, atk: 0, def: 60, crit: 0, crit_damage: 0, move_speed: -15, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'bronze_shield',
        name: 'Thanh Đồng Giáp Kích',
        type: 'passive',
        description: 'Gia tăng vĩnh viễn lượng phòng ngự vật lý.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Vô Lực Cổ',
      rank: 3,
      element: 'poison',
      role: 'control',
      quality: 'rare',
      description: 'Làm rã rời cơ bắp đối phương, khiến đối phương giảm mạnh lực tấn công.',
      sprite: 'gu_weaken',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 120, atk: 30, def: 20, crit: 5, crit_damage: 0, move_speed: 5, attack_speed: 5, life_steal: 2 },
    skills: [
      {
        skill_id: 'weaken_mist',
        name: 'Hủ Thực Độc Sương',
        type: 'active',
        description: 'Tỏa làn sương độc làm giảm 20% sát thương vật lý của đối thủ.',
        cooldown: 7,
        damage_multiplier: 90,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Phi Tốc Cổ',
      rank: 3,
      element: 'wind',
      role: 'utility',
      quality: 'rare',
      description: 'Cổ trùng ký sinh ở chân, tăng mạnh tốc độ di chuyển và chạy trốn.',
      sprite: 'gu_speed',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 0, atk: 10, def: 5, crit: 5, crit_damage: 10, move_speed: 50, attack_speed: 20, life_steal: 0 },
    skills: [
      {
        skill_id: 'dash_speed',
        name: 'Tật Tốc Hành',
        type: 'passive',
        description: 'Tăng mạnh tốc độ di chuyển và né tránh đòn đánh.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Nhai Tí Cổ',
      rank: 4,
      element: 'physical',
      role: 'damage',
      quality: 'epic',
      description: 'Hóa thân của lòng căm phẫn, tăng mạnh sát thương đòn đánh sau khi chịu đòn.',
      sprite: 'gu_yazi',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 200, atk: 130, def: 10, crit: 18, crit_damage: 40, move_speed: 10, attack_speed: 12, life_steal: 5 },
    skills: [
      {
        skill_id: 'rage_strike',
        name: 'Nhai Tí Tất Báo',
        type: 'active',
        description: 'Vung một đao căm hờn gây sát thương bạo kích cực lớn.',
        cooldown: 5,
        damage_multiplier: 280,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Ngự Thú Cổ',
      rank: 4,
      element: 'wood',
      role: 'summon',
      quality: 'epic',
      description: 'Thuần phục và ra lệnh cho dã thú hoang dã bảo vệ chủ nhân.',
      sprite: 'gu_beastcontrol',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 450, atk: 40, def: 40, crit: 5, crit_damage: 10, move_speed: 0, attack_speed: 0, life_steal: 5 },
    skills: [
      {
        skill_id: 'summon_beast',
        name: 'Mộc Thú Triệu Hồi',
        type: 'active',
        description: 'Triệu hồi hộ vệ gỗ hỗ trợ thu hút đòn đánh kẻ thù.',
        cooldown: 12,
        damage_multiplier: 50,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Hoàng Kim Cổ',
      rank: 4,
      element: 'earth',
      role: 'tank',
      quality: 'epic',
      description: 'Đúc bằng vàng ròng lấp lánh nâng đỡ sinh mệnh lực đến mức dồi dào tối đa.',
      sprite: 'gu_goldarmor',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 600, atk: 10, def: 95, crit: 0, crit_damage: 0, move_speed: -20, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'golden_defense',
        name: 'Kim Thân Bất Hoại',
        type: 'passive',
        description: 'Tăng mạnh HP tối đa và điểm phòng ngự vật lý.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Độc Bộ Thiên Hạ Cổ',
      rank: 5,
      element: 'poison',
      role: 'damage',
      quality: 'epic',
      description: 'Vua độc cổ phàm trần, chất độc ăn mòn xương cốt đối thủ cho đến chết.',
      sprite: 'gu_toxic',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 200, atk: 180, def: 20, crit: 20, crit_damage: 45, move_speed: 10, attack_speed: 15, life_steal: 8 },
    skills: [
      {
        skill_id: 'toxic_cloud',
        name: 'Độc Bộ Xâm Thực',
        type: 'active',
        description: 'Phun chất độc cực mạnh gây sát thương ăn mòn bỏ qua giáp.',
        cooldown: 6,
        damage_multiplier: 250,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Thái Cổ Cổ',
      rank: 5,
      element: 'space',
      role: 'utility',
      quality: 'epic',
      description: 'Rút cạn nguyên khí đất trời tích lũy dồi dào lượng Chân Nguyên dự trữ.',
      sprite: 'gu_ancient',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 800, atk: 50, def: 60, crit: 5, crit_damage: 15, move_speed: 25, attack_speed: 5, life_steal: 0 },
    skills: [
      {
        skill_id: 'essence_charge',
        name: 'Thái Cổ Khí Vận',
        type: 'passive',
        description: 'Tăng lượng Chân Nguyên tối đa cực lớn.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Kim Long Cổ',
      rank: 5,
      element: 'physical',
      role: 'damage',
      quality: 'epic',
      description: 'Hóa Long trảo càn quét phá hủy mọi thứ cản đường.',
      sprite: 'gu_golddragon',
      is_immortal: 'false',
      unique_world: 'false',
      max_enhance: 20,
      can_evolve: 'true',
    },
    stats: { hp: 300, atk: 210, def: 35, crit: 25, crit_damage: 50, move_speed: 20, attack_speed: 20, life_steal: 5 },
    skills: [
      {
        skill_id: 'dragon_claw',
        name: 'Kim Long Trảo Kích',
        type: 'active',
        description: 'Cào xé kẻ địch chấn động gây choáng và đẩy lui.',
        cooldown: 5,
        damage_multiplier: 290,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Xuân Thu Thiền',
      rank: 6,
      element: 'time',
      role: 'utility',
      quality: 'legendary',
      description: 'Lục Chuyển Tiên Cổ đứng đầu Thập Đại Kỳ Cổ thế giới, chứa đựng dòng chảy thời gian.',
      sprite: 'gu_springautumn',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 2000, atk: 200, def: 150, crit: 30, crit_damage: 80, move_speed: 50, attack_speed: 30, life_steal: 15 },
    skills: [
      {
        skill_id: 'time_reverse',
        name: 'Xuân Thu Nghịch Chuyển',
        type: 'active',
        description: 'Hồi phục toàn bộ sinh mệnh khi lượng HP cạn kiệt (Hồi sinh).',
        cooldown: 60,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Giang Sơn Như Họa Cổ',
      rank: 6,
      element: 'earth',
      role: 'support',
      quality: 'legendary',
      description: 'Lục Chuyển Tiên Cổ có thể hồi phục sông núi địa hình bị phá hủy về trạng thái cũ.',
      sprite: 'gu_landscape',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 3000, atk: 50, def: 250, crit: 0, crit_damage: 0, move_speed: 20, attack_speed: 0, life_steal: 0 },
    skills: [
      {
        skill_id: 'restore_terrain',
        name: 'Giang Sơn Như Cựu',
        type: 'passive',
        description: 'Tạo giáp bảo hộ giảm sát thương nhận vào 20% cho đồng đội lân cận.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Nhân Như Cựu Cổ',
      rank: 6,
      element: 'time',
      role: 'support',
      quality: 'legendary',
      description: 'Lục Chuyển Tiên Cổ chữa trị và khôi phục cơ thể con người về trạng thái 1 giây trước.',
      sprite: 'gu_manasbefore',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 2500, atk: 50, def: 180, crit: 5, crit_damage: 10, move_speed: 30, attack_speed: 10, life_steal: 0 },
    skills: [
      {
        skill_id: 'heal_man',
        name: 'Nhân Như Thuở Trước',
        type: 'active',
        description: 'Hồi phục lập tức 50% lượng máu đã mất.',
        cooldown: 15,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Thần Du Cổ',
      rank: 6,
      element: 'space',
      role: 'utility',
      quality: 'legendary',
      description: 'Lục Chuyển Tiên Cổ truyền thuyết, cho phép dịch chuyển tự do trong say xỉn.',
      sprite: 'gu_divinetravel',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 1000, atk: 100, def: 80, crit: 15, crit_damage: 30, move_speed: 100, attack_speed: 50, life_steal: 0 },
    skills: [
      {
        skill_id: 'teleport_drunk',
        name: 'Thần Du Tam Giới',
        type: 'active',
        description: 'Dịch chuyển tức thời đến một vị trí ngẫu nhiên trên bản đồ.',
        cooldown: 20,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Điên Đảo Càn Khôn Cổ',
      rank: 7,
      element: 'space',
      role: 'control',
      quality: 'legendary',
      description: 'Thất Chuyển Tiên Cổ làm hỗn loạn phương hướng và trật tự đất trời.',
      sprite: 'gu_chaos',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 4000, atk: 450, def: 300, crit: 25, crit_damage: 70, move_speed: 40, attack_speed: 25, life_steal: 10 },
    skills: [
      {
        skill_id: 'chaos_control',
        name: 'Điên Đảo Nhất Thế',
        type: 'active',
        description: 'Làm đảo lộn chuyển động kẻ thù và gây câm lặng trong 4 giây.',
        cooldown: 12,
        damage_multiplier: 180,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Kiếm Tôn Cổ',
      rank: 7,
      element: 'physical',
      role: 'damage',
      quality: 'legendary',
      description: 'Thất Chuyển Tiên Cổ ngưng tụ kiếm khí vương giả chém sắt như bùn.',
      sprite: 'gu_swordmonarch',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 1500, atk: 650, def: 100, crit: 40, crit_damage: 90, move_speed: 30, attack_speed: 35, life_steal: 5 },
    skills: [
      {
        skill_id: 'monarch_slash',
        name: 'Kiếm Tôn Hủy Diệt',
        type: 'active',
        description: 'Vung kiếm chém ra luồng sáng gây sát thương chí mạng cực cao.',
        cooldown: 5,
        damage_multiplier: 380,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Thiên Chỉ Cổ',
      rank: 8,
      element: 'light',
      role: 'damage',
      quality: 'legendary',
      description: 'Bát Chuyển Tiên Cổ uy lực vô biên ngưng tụ chùm sáng hủy thiên diệt địa.',
      sprite: 'gu_heavenfinger',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 8000, atk: 1200, def: 500, crit: 50, crit_damage: 120, move_speed: 50, attack_speed: 40, life_steal: 15 },
    skills: [
      {
        skill_id: 'heaven_finger',
        name: 'Thiên Chỉ Diệt Thế',
        type: 'active',
        description: 'Phóng cột sáng từ bầu trời gây sát thương diện rộng.',
        cooldown: 8,
        damage_multiplier: 450,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Đại Đồng Cổ',
      rank: 8,
      element: 'wind',
      role: 'support',
      quality: 'legendary',
      description: 'Bát Chuyển Tiên Cổ mang sức mạnh kết nối vạn vật làm một.',
      sprite: 'gu_unity',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 12000, atk: 300, def: 800, crit: 10, crit_damage: 30, move_speed: 30, attack_speed: 20, life_steal: 20 },
    skills: [
      {
        skill_id: 'unity_armor',
        name: 'Đồng Tâm Hợp Lực',
        type: 'passive',
        description: 'Phân tán 30% sát thương nhận vào cho các cổ trùng đang trang bị.',
        cooldown: 0,
        damage_multiplier: 0,
        target_type: 'self',
        aoe_radius: null,
      },
    ],
  },
  {
    template: {
      name: 'Xuân Thu Tôn Thiền',
      rank: 9,
      element: 'time',
      role: 'utility',
      quality: 'legendary',
      description: 'Cửu Chuyển Tiên Tôn Cổ tối thượng, kiểm soát tuyệt đối dòng sông thời gian.',
      sprite: 'gu_venerablecicada',
      is_immortal: 'true',
      unique_world: 'true',
      max_enhance: 20,
      can_evolve: 'false',
    },
    stats: { hp: 30000, atk: 3000, def: 2000, crit: 60, crit_damage: 200, move_speed: 150, attack_speed: 60, life_steal: 30 },
    skills: [
      {
        skill_id: 'chronos_strike',
        name: 'Thời Không Vĩnh Hằng',
        type: 'active',
        description: 'Dừng thời gian của kẻ thù lân cận trong 5 giây và gây sát thương khủng khiếp.',
        cooldown: 30,
        damage_multiplier: 600,
        target_type: 'single',
        aoe_radius: null,
      },
    ],
  },
];

export const guSynergySeeds = [
  {
    gu_a: '', // filled at runtime with Hỏa Cổ template ID
    gu_b: '', // filled at runtime with Phong Cổ template ID
    result_name: 'Hỏa Phong Bạo',
    result_description: 'Hỏa + Phong = Bão Lửa. Tăng 15% sát thương Hỏa.',
    result_skill_id: 'fire_storm',
    bonus_hp: 0,
    bonus_atk: 15,
    bonus_def: 0,
  },
];

export const equipmentSeeds = [
  {
    name: 'Thanh Đồng Kiếm',
    type: 'weapon',
    slot: 'main_hand',
    tier: 'common',
    base_hp: 0,
    base_atk: 25,
    base_def: 0,
    base_crit: 5,
    required_level: 1,
    description: 'Thanh kiếm đồng xanh cổ xưa, vẫn còn sắc bén sau bao năm.',
    icon: 'eq_vu_khi_st',
  },
  {
    name: 'Mộc Trượng',
    type: 'weapon',
    slot: 'main_hand',
    tier: 'common',
    base_hp: 50,
    base_atk: 15,
    base_def: 0,
    base_crit: 0,
    required_level: 1,
    description: 'Trượng gỗ trăm năm, có linh khí nhẹ nhàng.',
    icon: 'eq_vu_khi_h',
  },
  {
    name: 'Liệp Cung',
    type: 'weapon',
    slot: 'main_hand',
    tier: 'common',
    base_hp: 0,
    base_atk: 20,
    base_def: 0,
    base_crit: 10,
    required_level: 1,
    description: 'Cung săn bắn của thợ săn Bắc Nguyên.',
    icon: 'eq_vu_khi_pt',
  },
  {
    name: 'Bì Giáp',
    type: 'armor',
    slot: 'body',
    tier: 'common',
    base_hp: 100,
    base_atk: 0,
    base_def: 15,
    base_crit: 0,
    required_level: 1,
    description: 'Giáp da thú đơn giản nhưng chắc chắn.',
    icon: 'eq_giap_st',
  },
  {
    name: 'Mộc Thuẫn',
    type: 'armor',
    slot: 'off_hand',
    tier: 'common',
    base_hp: 50,
    base_atk: 0,
    base_def: 25,
    base_crit: 0,
    required_level: 1,
    description: 'Thuẫn gỗ cứng cáp, chặn được hầu hết đòn tấn công nhẹ.',
    icon: 'eq_giap_h',
  },
];

export const recipeSeeds = [
  {
    name: 'Rèn Thanh Đồng Kiếm',
    result_type: 'equipment',
    result_name: 'Thanh Đồng Kiếm',
    required_gold: 200,
    success_rate: 80,
    min_realm: 0,
    materials: [
      { item_name: 'Quặng Sắt', quantity: 3 },
    ],
  },
  {
    name: 'Chế Bì Giáp',
    result_type: 'equipment',
    result_name: 'Bì Giáp',
    required_gold: 150,
    success_rate: 80,
    min_realm: 0,
    materials: [
      { item_name: 'Da Thú', quantity: 3 },
    ],
  },
  {
    name: 'Chế Dược Hoàn Sơ Cấp',
    result_type: 'item',
    result_name: 'Dược Hoàn Sơ Cấp',
    required_gold: 100,
    success_rate: 90,
    min_realm: 0,
    materials: [
      { item_name: 'Thảo Dược', quantity: 2 },
    ],
  },
];

export const bacNguyenMonsterSeeds = [
  {
    ref: 'wolf_01',
    name: 'Sói Tuyết',
    realm: 'pham_nhan',
    hp: 55,
    atk: 10,
    def: 3,
    speed: 5,
    element: 'ice',
    sprite: 'mob_wolf',
    drop_table: JSON.stringify([
      { itemName: 'Lông Thú', chance: 0.7, minQuantity: 1, maxQuantity: 3 },
      { itemName: 'Đá Linh Hồn', chance: 0.2, minQuantity: 1, maxQuantity: 3 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 30,
  },
  {
    ref: 'bear_01',
    name: 'Gấu Trắng',
    realm: 'pham_nhan',
    hp: 140,
    atk: 18,
    def: 10,
    speed: 3,
    element: 'physical',
    sprite: 'mob_bear',
    drop_table: JSON.stringify([
      { itemName: 'Da Thú', chance: 0.6, minQuantity: 1, maxQuantity: 3 },
      { itemName: 'Đá Linh Hồn', chance: 0.25, minQuantity: 2, maxQuantity: 5 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 45,
  },
  {
    ref: 'rabbit_01',
    name: 'Thỏ Tuyết',
    realm: 'pham_nhan',
    hp: 50,
    atk: 8,
    def: 2,
    speed: 8,
    element: 'ice',
    sprite: 'mob_rabbit',
    drop_table: JSON.stringify([
      { itemName: 'Lông Thú', chance: 0.5, minQuantity: 1, maxQuantity: 2 },
      { itemName: 'Thảo Dược', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 20,
  },
  {
    ref: 'eagle_01',
    name: 'Ưng Bắc Nguyên',
    realm: 'luyen_khi',
    hp: 130,
    atk: 20,
    def: 9,
    speed: 7,
    element: 'wind',
    sprite: 'mob_eagle',
    drop_table: JSON.stringify([
      { itemName: 'Đá Linh Hồn', chance: 0.4, minQuantity: 2, maxQuantity: 6 },
      { itemName: 'Lông Thú', chance: 0.5, minQuantity: 1, maxQuantity: 3 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 50,
  },
];

export const bossSeeds = [
  {
    ref: 'boss_wolf_king',
    name: 'Bạch Lang Vương',
    realm: 'luyen_khi',
    hp: 800,
    atk: 35,
    def: 20,
    speed: 6,
    element: 'ice',
    sprite: 'boss_wolf_king',
    drop_table: JSON.stringify([
      { itemName: 'Đá Linh Hồn', chance: 1.0, minQuantity: 10, maxQuantity: 20 },
      { itemName: 'Tinh Hoa Băng', chance: 1.0, minQuantity: 1, maxQuantity: 1 },
      { itemName: 'Da Thú', chance: 0.8, minQuantity: 3, maxQuantity: 6 },
    ]),
    map_id: 'bac_nguyen',
    respawn_time: 300,
  },
];

export const worldMapSeeds = [
  { ref: 'lang_cothao', name: 'Làng Cổ Thảo', region: 'bac_nguyen', recommended_realm: 1, is_safe_zone: 'true', background: 'bg_village', width: 1500, height: 1500 },
  { ref: 'dongco_hoang', name: 'Đồng Cỏ Hoang', region: 'bac_nguyen', recommended_realm: 1, is_safe_zone: 'false', background: 'bg_grassland', width: 2500, height: 2000 },
  { ref: 'rung_tuyet', name: 'Rừng Tuyết', region: 'bac_nguyen', recommended_realm: 1, is_safe_zone: 'false', background: 'bg_snow_forest', width: 3000, height: 2500 },
  { ref: 'dinh_bangphong', name: 'Đỉnh Băng Phong', region: 'bac_nguyen', recommended_realm: 2, is_safe_zone: 'false', background: 'bg_ice_peak', width: 2000, height: 2000 },
  { ref: 'canhdong_tuyet', name: 'Cánh Đồng Tuyết', region: 'bac_nguyen', recommended_realm: 1, is_safe_zone: 'false', background: 'bg_snow_field', width: 2500, height: 2000 },
];

export const mapPortalSeeds = [
  { from_map_ref: 'lang_cothao', to_map_ref: 'dongco_hoang', from_x: 1400, from_y: 750, to_x: 100, to_y: 1000, portal_name: 'Cổng Làng → Đồng Cỏ' },
  { from_map_ref: 'dongco_hoang', to_map_ref: 'lang_cothao', from_x: 80, from_y: 1000, to_x: 1350, to_y: 750, portal_name: 'Quay về Làng' },
  { from_map_ref: 'dongco_hoang', to_map_ref: 'rung_tuyet', from_x: 2400, from_y: 1000, to_x: 100, to_y: 1250, portal_name: 'Đường Rừng → Núi' },
  { from_map_ref: 'rung_tuyet', to_map_ref: 'dongco_hoang', from_x: 80, from_y: 1250, to_x: 2350, to_y: 1000, portal_name: 'Quay về Đồng Cỏ' },
  { from_map_ref: 'rung_tuyet', to_map_ref: 'dinh_bangphong', from_x: 1500, from_y: 50, to_x: 1000, to_y: 1900, portal_name: 'Dốc Băng' },
  { from_map_ref: 'dinh_bangphong', to_map_ref: 'rung_tuyet', from_x: 1000, from_y: 1950, to_x: 1450, to_y: 100, portal_name: 'Xuống Rừng' },
  { from_map_ref: 'dinh_bangphong', to_map_ref: 'canhdong_tuyet', from_x: 100, from_y: 1000, to_x: 2400, to_y: 1000, portal_name: 'Triền Núi → Đồng' },
  { from_map_ref: 'canhdong_tuyet', to_map_ref: 'dinh_bangphong', from_x: 2450, from_y: 1000, to_x: 150, to_y: 1000, portal_name: 'Lên Núi' },
];

export const mapSpawnSeeds = [
  // Làng Cổ Thảo
  { map_ref: 'lang_cothao', spawn_type: 'monster', spawn_ref: 'Thỏ Tuyết', x: 800, y: 700, respawn_time: 15 },
  { map_ref: 'lang_cothao', spawn_type: 'monster', spawn_ref: 'Thỏ Tuyết', x: 700, y: 800, respawn_time: 15 },
  { map_ref: 'lang_cothao', spawn_type: 'npc', spawn_ref: 'Trưởng làng', x: 500, y: 400, respawn_time: 30 },
  { map_ref: 'lang_cothao', spawn_type: 'npc', spawn_ref: 'Thợ rèn', x: 600, y: 300, respawn_time: 30 },
  { map_ref: 'lang_cothao', spawn_type: 'npc', spawn_ref: 'Thương nhân', x: 400, y: 500, respawn_time: 30 },
  { map_ref: 'lang_cothao', spawn_type: 'npc', spawn_ref: 'Trưởng lão', x: 700, y: 450, respawn_time: 30 },
  // Đồng Cỏ Hoang
  { map_ref: 'dongco_hoang', spawn_type: 'monster', spawn_ref: 'Sói Tuyết', x: 500, y: 600, respawn_time: 30 },
  { map_ref: 'dongco_hoang', spawn_type: 'monster', spawn_ref: 'Sói Tuyết', x: 1200, y: 400, respawn_time: 30 },
  { map_ref: 'dongco_hoang', spawn_type: 'monster', spawn_ref: 'Thỏ Tuyết', x: 800, y: 300, respawn_time: 20 },
  { map_ref: 'dongco_hoang', spawn_type: 'monster', spawn_ref: 'Thỏ Tuyết', x: 1500, y: 700, respawn_time: 20 },
  // Rừng Tuyết
  { map_ref: 'rung_tuyet', spawn_type: 'monster', spawn_ref: 'Sói Tuyết', x: 600, y: 800, respawn_time: 30 },
  { map_ref: 'rung_tuyet', spawn_type: 'monster', spawn_ref: 'Gấu Trắng', x: 1200, y: 500, respawn_time: 45 },
  { map_ref: 'rung_tuyet', spawn_type: 'monster', spawn_ref: 'Thiết Bì Cự Hùng', x: 2000, y: 1000, respawn_time: 60 },
  { map_ref: 'rung_tuyet', spawn_type: 'monster', spawn_ref: 'Thỏ Tuyết', x: 800, y: 1500, respawn_time: 20 },
  { map_ref: 'rung_tuyet', spawn_type: 'npc', spawn_ref: 'Bia Đá Cổ', x: 1000, y: 800, respawn_time: 30 },
  { map_ref: 'dinh_bangphong', spawn_type: 'monster', spawn_ref: 'Ưng Bắc Nguyên', x: 500, y: 500, respawn_time: 50 },
  { map_ref: 'dinh_bangphong', spawn_type: 'monster', spawn_ref: 'Ưng Bắc Nguyên', x: 1500, y: 600, respawn_time: 50 },
  { map_ref: 'dinh_bangphong', spawn_type: 'monster', spawn_ref: 'Sói Tuyết', x: 1000, y: 1200, respawn_time: 30 },
  { map_ref: 'dinh_bangphong', spawn_type: 'boss', spawn_ref: 'Bạch Lang Vương', x: 1000, y: 500, respawn_time: 300 },
  { map_ref: 'dinh_bangphong', spawn_type: 'npc', spawn_ref: 'Bạch Lang Vương', x: 1000, y: 450, respawn_time: 30 },
  // Cánh Đồng Tuyết
  { map_ref: 'canhdong_tuyet', spawn_type: 'monster', spawn_ref: 'Sói Tuyết', x: 700, y: 500, respawn_time: 30 },
  { map_ref: 'canhdong_tuyet', spawn_type: 'monster', spawn_ref: 'Thỏ Tuyết', x: 400, y: 1000, respawn_time: 20 },
  { map_ref: 'canhdong_tuyet', spawn_type: 'monster', spawn_ref: 'Gấu Trắng', x: 1800, y: 800, respawn_time: 45 },
];

export const dialogueSeeds = [
  {
    ref: 'dlg_village_chief_intro_1',
    npc_ref: 'Trưởng làng',
    order_index: 0,
    text: 'Chào mừng ngươi đến Làng Cổ Thảo, lữ khách. Ta là Trưởng làng nơi đây. Ngươi có vẻ mệt mỏi sau biến cố ngất xỉu giữa bão tuyết Bắc Nguyên...',
    speaker: 'Trưởng làng',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_village_chief_intro_2' }]),
  },
  {
    ref: 'dlg_village_chief_intro_2',
    npc_ref: 'Trưởng làng',
    order_index: 1,
    text: 'Bắc Nguyên băng giá hoang vu, quanh năm tuyết phủ trắng xóa. Bộ lạc chúng ta sống nương tựa vào nhau, chống lại sự khắc nghiệt của thời tiết và bầy thú dữ.',
    speaker: 'Trưởng làng',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_village_chief_intro_3' }]),
  },
  {
    ref: 'dlg_village_chief_intro_3',
    npc_ref: 'Trưởng làng',
    order_index: 2,
    text: 'Tuy nhiên dạo gần đây, linh khí dao động dị thường. Bầy Sói Tuyết ở Đồng Cỏ Hoang trở nên vô cùng khát máu, tấn công liên tục vào rìa làng ta.',
    speaker: 'Trưởng làng',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_village_chief_intro_4' }]),
  },
  {
    ref: 'dlg_village_chief_intro_4',
    npc_ref: 'Trưởng làng',
    order_index: 3,
    text: 'Ngươi xuất hiện lúc này chính là cơ duyên. Hãy giúp làng tiêu diệt 3 con Sói Tuyết ở Đồng Cỏ Hoang phía Đông để lập công và chứng minh tu vi của mình.',
    speaker: 'Trưởng làng',
    choices: JSON.stringify([
      { text: 'Ta sẵn sàng giúp đỡ!', next_dialogue_ref: 'dlg_village_chief_accept' },
      { text: 'Bầy sói có nguy hiểm quá không?', next_dialogue_ref: 'dlg_village_chief_warn' },
    ]),
  },
  {
    ref: 'dlg_village_chief_warn',
    npc_ref: 'Trưởng làng',
    order_index: 4,
    text: 'Chúng di chuyển rất nhanh và tấn công theo bầy. Hãy sử dụng các kỹ năng và di chuyển linh hoạt để khắc chế chúng!',
    speaker: 'Trưởng làng',
    choices: JSON.stringify([{ text: 'Được, ta sẽ đi!', next_dialogue_ref: 'dlg_village_chief_accept' }]),
  },
  {
    ref: 'dlg_village_chief_accept',
    npc_ref: 'Trưởng làng',
    order_index: 5,
    text: 'Tốt lắm, dũng sĩ. Đồng Cỏ Hoang nằm ngay phía Đông cổng làng. Cầm lấy ít thuốc hồi phục này và lên đường!',
    speaker: 'Trưởng làng',
    set_flag: 'ch1_intro_done',
  },
  {
    ref: 'dlg_village_chief_thanks',
    npc_ref: 'Trưởng làng',
    order_index: 6,
    text: 'Ngươi quả thực rất xuất sắc! Bầy Sói Tuyết đã bị đẩy lui. Tuy nhiên... ta e rằng hiểm họa thật sự vẫn còn chực chờ trên Đỉnh Băng Phong.',
    speaker: 'Trưởng làng',
    condition_flag: 'ch1_wolves_hunted',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_village_chief_thanks_2' }]),
  },
  {
    ref: 'dlg_village_chief_thanks_2',
    npc_ref: 'Trưởng làng',
    order_index: 7,
    text: 'Trưởng lão của làng am hiểu lịch sử cổ đại và đang đợi ngươi ở phía Bắc làng để truyền thụ bí mật tối thượng. Hãy đến gặp ông ấy ngay.',
    speaker: 'Trưởng làng',
    set_flag: 'ch1_sent_to_elder',
  },
  {
    ref: 'dlg_elder_intro_1',
    npc_ref: 'Trưởng lão',
    order_index: 0,
    text: 'Ta đã chờ ngươi từ rất lâu rồi... Kẻ mang trong mình hơi thở của Sinh Cổ...',
    speaker: 'Trưởng lão',
    choices: JSON.stringify([{ text: 'Trưởng lão biết về Sinh Cổ?', next_dialogue_ref: 'dlg_elder_intro_2' }]),
  },
  {
    ref: 'dlg_elder_intro_2',
    npc_ref: 'Trưởng lão',
    order_index: 1,
    text: 'Đúng vậy. Linh khí thiên địa vốn là thứ Thiên Đạo ban phát cho nhân gian, nhằm cầm tù tư duy tu sĩ. Nhưng Cổ Đạo lại khác — Cổ là tinh hoa của trời đất, là con đường nghịch thiên cải mệnh!',
    speaker: 'Trưởng lão',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_elder_intro_3' }]),
  },
  {
    ref: 'dlg_elder_intro_3',
    npc_ref: 'Trưởng lão',
    order_index: 2,
    text: 'Ngàn năm trước, vị tu sĩ Cổ Đạo vĩ đại đã dùng mạng sống của mình phong ấn yêu thú Bạch Lang Vương trên Đỉnh Băng Phong. Nhưng nay phong ấn sắp vỡ, yêu thú sắp trỗi dậy tàn sát Bắc Nguyên.',
    speaker: 'Trưởng lão',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_elder_intro_4' }]),
  },
  {
    ref: 'dlg_elder_intro_4',
    npc_ref: 'Trưởng lão',
    order_index: 3,
    text: 'Ta muốn ngươi vượt qua Rừng Tuyết hiểm trở, tiến thẳng lên Đỉnh Băng Phong để gia cố phong ấn, hoặc tiêu diệt hoàn toàn Bạch Lang Vương.',
    speaker: 'Trưởng lão',
    condition_flag: 'ch1_sent_to_elder',
    choices: JSON.stringify([
      { text: 'Ta sẵn sàng đối mặt!', next_dialogue_ref: 'dlg_elder_accept' },
      { text: 'Con đường lên núi thế nào?', next_dialogue_ref: 'dlg_elder_path' },
    ]),
  },
  {
    ref: 'dlg_elder_path',
    npc_ref: 'Trưởng lão',
    order_index: 4,
    text: 'Đường lên núi cực kỳ gian nan, bị phong tỏa bởi con Thiết Bì Cự Hùng to lớn ở Rừng Tuyết. Ngươi cũng phải tìm kiếm Bia Đá Cổ trong rừng để giải mã cổ tự giúp tăng sức mạnh.',
    speaker: 'Trưởng lão',
    choices: JSON.stringify([{ text: 'Ta sẽ lên đường!', next_dialogue_ref: 'dlg_elder_accept' }]),
  },
  {
    ref: 'dlg_elder_accept',
    npc_ref: 'Trưởng lão',
    order_index: 5,
    text: 'Hãy đến gặp Thợ rèn trước khi rời làng. Ông ấy có thể giúp ngươi chế tạo vũ khí thích hợp chống lại hàn khí. Chúc ngươi may mắn!',
    speaker: 'Trưởng lão',
    set_flag: 'ch1_sent_to_blacksmith',
  },
  {
    ref: 'dlg_blacksmith_intro_1',
    npc_ref: 'Thợ rèn',
    order_index: 0,
    text: 'Ồ, ngươi chính là lữ khách muốn thách thức Đỉnh Băng Phong? Trưởng lão đã truyền tin cho ta rồi.',
    speaker: 'Thợ rèn',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_blacksmith_intro_2' }]),
  },
  {
    ref: 'dlg_blacksmith_intro_2',
    npc_ref: 'Thợ rèn',
    order_index: 1,
    text: 'Để chém sắt như bùn trên đỉnh núi lạnh buốt ấy, vũ khí thường không ăn thua. Ta cần rèn cho ngươi chiếc Kiếm Băng Hàn từ linh thạch thô.',
    speaker: 'Thợ rèn',
    condition_flag: 'ch1_sent_to_blacksmith',
    choices: JSON.stringify([
      { text: 'Linh thạch thô lấy ở đâu?', next_dialogue_ref: 'dlg_blacksmith_quest' },
    ]),
  },
  {
    ref: 'dlg_blacksmith_quest',
    npc_ref: 'Thợ rèn',
    order_index: 2,
    text: 'Đám Đá Linh Hồn lấp lánh có thể tìm thấy khi khai thác quặng hoặc đánh bại quái thú ở Đồng Cỏ Hoang. Hãy mang cho ta 5 mảnh Đá Linh Hồn, ta sẽ rèn kiếm cho ngươi!',
    speaker: 'Thợ rèn',
    set_flag: 'ch1_blacksmith_quest',
  },
  {
    ref: 'dlg_blacksmith_reward',
    npc_ref: 'Thợ rèn',
    order_index: 3,
    text: 'Tốt lắm, nguyên liệu rất chất lượng! Đợi một chút... Keng! Keng! Kiếm Băng Hàn đã thành! Hãy giữ lấy nó và tiến vào Rừng Tuyết.',
    speaker: 'Thợ rèn',
    condition_flag: 'ch1_reached_peak',
    set_flag: 'ch1_got_weapon',
  },
  {
    ref: 'dlg_merchant_intro',
    npc_ref: 'Thương nhân',
    order_index: 0,
    text: 'Chào khách quý! Hàng hóa dược liệu, đan dược của ta là tốt nhất vùng Bắc Nguyên này rồi. Có mua gì chuẩn bị lên núi không?',
    speaker: 'Thương nhân',
  },
  {
    ref: 'dlg_stele_read_1',
    npc_ref: 'Bia Đá Cổ',
    order_index: 0,
    text: 'Tấm bia đá phủ đầy rêu phong và băng tuyết cổ xưa... Trên mặt đá khắc dòng chữ: "Cổ Đạo chi linh, sinh tử luân hồi. Kẻ kế thừa hãy phá vỡ xiềng xích của Thiên Đạo..."',
    speaker: 'Bia Đá Cổ',
    choices: JSON.stringify([{ text: 'Tiếp tục đọc cổ tự', next_dialogue_ref: 'dlg_stele_read_2' }]),
  },
  {
    ref: 'dlg_stele_read_2',
    npc_ref: 'Bia Đá Cổ',
    order_index: 1,
    text: '"...Sinh Cổ thức tỉnh cần hấp thu Tinh Hoa Băng cực hàn từ Bạch Lang Vương để phá giải xiềng xích Nhất Chuyển Khiếu, đột phá lên Nhị Chuyển Cảnh Giới!"',
    speaker: 'Bia Đá Cổ',
    set_flag: 'ch1_stele_read',
  },
  {
    ref: 'dlg_boss_confront_1',
    npc_ref: 'Bạch Lang Vương',
    order_index: 0,
    text: 'Gừ... lũ phàm nhân kiến hôi! Hào quang trên người ngươi... là Sinh Cổ của Cổ Đạo?! Ngươi dám quấy rầy giấc ngủ ngàn năm của ta!',
    speaker: 'Bạch Lang Vương',
    choices: JSON.stringify([{ text: 'Ngươi chính là yêu thú Bạch Lang Vương!', next_dialogue_ref: 'dlg_boss_confront_2' }]),
  },
  {
    ref: 'dlg_boss_confront_2',
    npc_ref: 'Bạch Lang Vương',
    order_index: 1,
    text: 'Ha ha ha! Phong ấn ngàn năm đã vỡ nát! Lực lượng của Thiên Đạo cũng không thể giam cầm ta nữa! Hãy trở thành huyết thực cho ta!',
    speaker: 'Bạch Lang Vương',
    set_flag: 'ch1_boss_confronted',
  },
];

export const chapter1QuestSeeds = [
  {
    ref: 'q_ch1_awaken',
    name: 'Tỉnh Giấc Mộng',
    type: 'main',
    description: 'Ngươi tỉnh dậy mệt mỏi giữa vùng tuyết lạnh Bắc Nguyên. Hãy tìm gặp Trưởng làng Cổ Thảo để hỏi han bối cảnh.',
    npc_giver_ref: 'Trưởng làng',
    objectives: JSON.stringify([
      { type: 'talk', target: 'Trưởng làng', count: 1, description: 'Nói chuyện với Trưởng làng' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 50 },
      { type: 'exp', amount: 20 },
    ]),
    flag_complete: 'ch1_awakened',
    flag_required: null,
    min_realm: 1,
  },
  {
    ref: 'q_ch1_wolves',
    name: 'Mối Đe Dọa Sói Tuyết',
    type: 'main',
    description: 'Bầy Sói Tuyết đang quấy nhiễu dân làng. Hãy tiến sang Đồng Cỏ Hoang phía Đông và tiêu diệt 3 con Sói Tuyết để trừ họa.',
    npc_giver_ref: 'Trưởng làng',
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch1_awakened' },
    ]),
    objectives: JSON.stringify([
      { type: 'kill', target: 'Sói Tuyết', count: 3, description: 'Tiêu diệt Sói Tuyết ở Đồng Cỏ Hoang' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 100 },
      { type: 'exp', amount: 50 },
      { type: 'item', item_ref: 'Thảo Dược', amount: 3 },
    ]),
    flag_required: 'ch1_awakened',
    flag_complete: 'ch1_wolves_hunted',
    min_realm: 1,
  },
  {
    ref: 'q_ch1_prophecy',
    name: 'Lời Tiên Tri Cổ',
    type: 'main',
    description: 'Nghe lời chỉ dẫn từ Trưởng làng để tìm gặp Trưởng lão bộ lạc ở phía Bắc làng, tiếp thu bí mật lịch sử Cổ Đạo.',
    npc_giver_ref: 'Trưởng làng',
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch1_wolves_hunted' },
    ]),
    objectives: JSON.stringify([
      { type: 'talk', target: 'Trưởng lão', count: 1, description: 'Trò chuyện nghe truyền thụ từ Trưởng lão' },
    ]),
    rewards: JSON.stringify([
      { type: 'exp', amount: 50 },
      { type: 'item', item_ref: 'Mảnh Bản Đồ', amount: 1 },
    ]),
    flag_required: 'ch1_wolves_hunted',
    flag_complete: 'ch1_prophecy_heard',
    min_realm: 1,
  },
  {
    ref: 'q_ch1_journey',
    name: 'Vượt Qua Rừng Tuyết',
    type: 'main',
    description: 'Đường lên núi bị cản trở bởi Thiết Bì Cự Hùng. Hãy đánh bại nó, giải mật Bia Đá Cổ chứa cổ thư pháp tắc để thăng tiến linh khiếu.',
    npc_giver_ref: 'Trưởng lão',
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch1_prophecy_heard' },
    ]),
    objectives: JSON.stringify([
      { type: 'kill', target: 'Thiết Bì Cự Hùng', count: 1, description: 'Tiêu diệt Thiết Bì Cự Hùng chặn đường' },
      { type: 'talk', target: 'Bia Đá Cổ', count: 1, description: 'Đọc và giải mã Bia Đá Cổ trong Rừng Tuyết' },
      { type: 'reach', target: 'dinh_bangphong', count: 1, description: 'Vượt rừng tiến lên Đỉnh Băng Phong' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 200 },
      { type: 'exp', amount: 100 },
      { type: 'item', item_ref: 'Kiếm Băng Hàn', amount: 1 },
    ]),
    flag_required: 'ch1_prophecy_heard',
    flag_complete: 'ch1_reached_peak',
    min_realm: 1,
  },
  {
    ref: 'q_ch1_boss',
    name: 'Bạch Lang Vương',
    type: 'main',
    description: 'Bạch Lang Vương ngàn năm chuẩn bị thức tỉnh hoàn toàn. Hãy đối mặt và tiêu diệt nó trên Đỉnh Băng Phong để đột phá Nhị Chuyển.',
    npc_giver_ref: null,
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch1_reached_peak' },
    ]),
    objectives: JSON.stringify([
      { type: 'kill', target: 'Bạch Lang Vương', count: 1, description: 'Đánh bại yêu thú Bạch Lang Vương' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 500 },
      { type: 'exp', amount: 300 },
      { type: 'item', item_ref: 'Tinh Hoa Băng', amount: 1 },
      { type: 'spirit_stone', amount: 10 },
    ]),
    flag_required: 'ch1_reached_peak',
    flag_complete: 'ch1_complete',
    min_realm: 1,
  },
];

// ============================================================
// CHAPTER 2: NAM CƯƠNG — Seed Data
// ============================================================

export const namCuongMapSeeds = [
  {
    ref: 'tran_doc_tri',
    name: 'Trấn Độc Trì',
    region: 'nam_cuong',
    recommended_realm: 3,
    is_safe_zone: 'true',
    background: 'bg_jungle_village',
    width: 1600,
    height: 1600,
  },
  {
    ref: 'rung_doc',
    name: 'Rừng Độc',
    region: 'nam_cuong',
    recommended_realm: 3,
    is_safe_zone: 'false',
    background: 'bg_poison_forest',
    width: 2800,
    height: 2200,
  },
  {
    ref: 'dam_lay_co',
    name: 'Đầm Lầy Cổ',
    region: 'nam_cuong',
    recommended_realm: 4,
    is_safe_zone: 'false',
    background: 'bg_ancient_swamp',
    width: 2500,
    height: 2000,
  },
  {
    ref: 'hang_van_doc',
    name: 'Hang Vạn Độc',
    region: 'nam_cuong',
    recommended_realm: 4,
    is_safe_zone: 'false',
    background: 'bg_poison_cave',
    width: 1800,
    height: 1800,
  },
];

export const namCuongNpcSeeds = [
  {
    name: 'Lão Độc Sư',
    sprite: 'char_5',
    faction: 'van_doc_mon',
    occupation: 'elder',
    mapId: 'tran_doc_tri',
    x: 800,
    y: 600,
    hasShop: 'false',
  },
  {
    name: 'Thương Nhân Độc Vật',
    sprite: 'char_4',
    faction: 'neutral',
    occupation: 'merchant',
    mapId: 'tran_doc_tri',
    x: 600,
    y: 800,
    hasShop: 'true',
  },
  {
    name: 'Kiếm Sư Tán Tu',
    sprite: 'char_3',
    faction: 'neutral',
    occupation: 'wanderer',
    mapId: 'tran_doc_tri',
    x: 1000,
    y: 700,
    hasShop: 'false',
  },
  {
    name: 'Vạn Độc Cổ Vương',
    sprite: 'boss_wan_du',
    faction: 'wild',
    occupation: 'story_boss',
    mapId: 'hang_van_doc',
    x: 900,
    y: 600,
    hasShop: 'false',
  },
];

export const namCuongMonsterSeeds = [
  {
    ref: 'doc_xa_01',
    name: 'Độc Xà',
    realm: 'pham_nhan',
    hp: 160,
    atk: 28,
    def: 8,
    speed: 6,
    element: 'poison',
    sprite: 'mob_snake',
    drop_table: JSON.stringify([
      { itemName: 'Nọc Độc', chance: 0.7, minQuantity: 1, maxQuantity: 3 },
      { itemName: 'Độc Thảo', chance: 0.3, minQuantity: 1, maxQuantity: 2 },
    ]),
    map_id: 'rung_doc',
    respawn_time: 35,
  },
  {
    ref: 'doc_chu_01',
    name: 'Độc Chu',
    realm: 'pham_nhan',
    hp: 140,
    atk: 25,
    def: 10,
    speed: 4,
    element: 'poison',
    sprite: 'mob_spider',
    drop_table: JSON.stringify([
      { itemName: 'Nọc Độc', chance: 0.6, minQuantity: 1, maxQuantity: 2 },
      { itemName: 'Đá Linh Hồn', chance: 0.3, minQuantity: 2, maxQuantity: 5 },
    ]),
    map_id: 'rung_doc',
    respawn_time: 40,
  },
  {
    ref: 'co_trung_hoang_da_01',
    name: 'Cổ Trùng Hoang Dã',
    realm: 'luyen_khi',
    hp: 320,
    atk: 42,
    def: 18,
    speed: 5,
    element: 'poison',
    sprite: 'mob_wildgu',
    drop_table: JSON.stringify([
      { itemName: 'Cổ Hoang Tinh', chance: 1.0, minQuantity: 1, maxQuantity: 1 },
      { itemName: 'Nọc Độc', chance: 0.5, minQuantity: 2, maxQuantity: 4 },
    ]),
    map_id: 'dam_lay_co',
    respawn_time: 90,
  },
  {
    ref: 'doc_phong_01',
    name: 'Độc Phong',
    realm: 'luyen_khi',
    hp: 280,
    atk: 38,
    def: 15,
    speed: 8,
    element: 'poison',
    sprite: 'mob_beeswarm',
    drop_table: JSON.stringify([
      { itemName: 'Độc Thảo', chance: 0.5, minQuantity: 2, maxQuantity: 5 },
      { itemName: 'Đá Linh Hồn', chance: 0.4, minQuantity: 3, maxQuantity: 8 },
    ]),
    map_id: 'dam_lay_co',
    respawn_time: 60,
  },
];

export const namCuongBossSeeds = [
  {
    ref: 'boss_wan_du',
    name: 'Vạn Độc Cổ Vương',
    realm: 'luyen_khi',
    hp: 2400,
    atk: 75,
    def: 40,
    speed: 5,
    element: 'poison',
    sprite: 'boss_wan_du',
    drop_table: JSON.stringify([
      { itemName: 'Cổ Hoang Tinh', chance: 1.0, minQuantity: 3, maxQuantity: 3 },
      { itemName: 'Đá Linh Hồn', chance: 1.0, minQuantity: 15, maxQuantity: 30 },
      { itemName: 'Luyện Cổ Đan', chance: 0.8, minQuantity: 2, maxQuantity: 5 },
    ]),
    map_id: 'hang_van_doc',
    respawn_time: 600,
  },
];

export const namCuongItemSeeds = [
  { name: 'Độc Thảo', type: 'material', description: 'Dược thảo hệ độc của Nam Cương, dùng để luyện đan', stackable: 'true', maxStack: 99, sellPrice: 5, sprite: 'gui_icon_herb' },
  { name: 'Nọc Độc', type: 'material', description: 'Nọc độc tinh chế từ rắn và nhện của Rừng Độc', stackable: 'true', maxStack: 99, sellPrice: 8, sprite: 'gui_icon_venom' },
  { name: 'Cổ Hoang Tinh', type: 'quest_item', description: 'Tinh hoa của Cổ Trùng Hoang Dã, ẩn chứa khí tức Cổ Đạo nguyên sơ', stackable: 'false', maxStack: 1, sellPrice: 0, sprite: 'gui_icon_essence' },
  { name: 'Luyện Cổ Đan', type: 'consumable', description: 'Đan dược luyện thành từ Độc Thảo Nam Cương, tăng cường Cổ Trùng tạm thời', stackable: 'true', maxStack: 20, sellPrice: 50, sprite: 'gui_icon_potion' },
];

export const namCuongPortalSeeds = [
  // Cross-chapter connection: Đỉnh Băng Phong → Trấn Độc Trì
  { from_map_ref: 'dinh_bangphong', to_map_ref: 'tran_doc_tri', from_x: 1900, from_y: 500, to_x: 150, to_y: 800, portal_name: 'Cổng Gió Nam → Nam Cương', requires_realm: 3 },
  // Return portal
  { from_map_ref: 'tran_doc_tri', to_map_ref: 'dinh_bangphong', from_x: 100, from_y: 800, to_x: 1850, to_y: 500, portal_name: 'Về Bắc Nguyên' },
  // Within Nam Cương
  { from_map_ref: 'tran_doc_tri', to_map_ref: 'rung_doc', from_x: 1500, from_y: 800, to_x: 150, to_y: 1100, portal_name: 'Vào Rừng Độc' },
  { from_map_ref: 'rung_doc', to_map_ref: 'tran_doc_tri', from_x: 100, from_y: 1100, to_x: 1450, to_y: 800, portal_name: 'Về Trấn Độc Trì' },
  { from_map_ref: 'rung_doc', to_map_ref: 'dam_lay_co', from_x: 2700, from_y: 1100, to_x: 150, to_y: 1000, portal_name: 'Đầm Lầy Cổ' },
  { from_map_ref: 'dam_lay_co', to_map_ref: 'rung_doc', from_x: 100, from_y: 1000, to_x: 2650, to_y: 1100, portal_name: 'Về Rừng Độc' },
  { from_map_ref: 'dam_lay_co', to_map_ref: 'hang_van_doc', from_x: 2400, from_y: 500, to_x: 150, to_y: 900, portal_name: 'Hang Vạn Độc' },
  { from_map_ref: 'hang_van_doc', to_map_ref: 'dam_lay_co', from_x: 100, from_y: 900, to_x: 2350, to_y: 500, portal_name: 'Trở Ra Đầm Lầy' },
];

export const namCuongSpawnSeeds = [
  // Trấn Độc Trì (safe zone)
  { map_ref: 'tran_doc_tri', spawn_type: 'npc', spawn_ref: 'Lão Độc Sư', x: 800, y: 600, respawn_time: 30 },
  { map_ref: 'tran_doc_tri', spawn_type: 'npc', spawn_ref: 'Thương Nhân Độc Vật', x: 600, y: 800, respawn_time: 30 },
  { map_ref: 'tran_doc_tri', spawn_type: 'npc', spawn_ref: 'Kiếm Sư Tán Tu', x: 1000, y: 700, respawn_time: 30 },
  // Rừng Độc
  { map_ref: 'rung_doc', spawn_type: 'monster', spawn_ref: 'Độc Xà', x: 600, y: 700, respawn_time: 35 },
  { map_ref: 'rung_doc', spawn_type: 'monster', spawn_ref: 'Độc Xà', x: 1400, y: 900, respawn_time: 35 },
  { map_ref: 'rung_doc', spawn_type: 'monster', spawn_ref: 'Độc Xà', x: 2100, y: 600, respawn_time: 35 },
  { map_ref: 'rung_doc', spawn_type: 'monster', spawn_ref: 'Độc Chu', x: 900, y: 1400, respawn_time: 40 },
  { map_ref: 'rung_doc', spawn_type: 'monster', spawn_ref: 'Độc Chu', x: 1800, y: 1600, respawn_time: 40 },
  { map_ref: 'rung_doc', spawn_type: 'monster', spawn_ref: 'Độc Chu', x: 2400, y: 1100, respawn_time: 40 },
  // Đầm Lầy Cổ
  { map_ref: 'dam_lay_co', spawn_type: 'monster', spawn_ref: 'Cổ Trùng Hoang Dã', x: 700, y: 600, respawn_time: 90 },
  { map_ref: 'dam_lay_co', spawn_type: 'monster', spawn_ref: 'Cổ Trùng Hoang Dã', x: 1600, y: 900, respawn_time: 90 },
  { map_ref: 'dam_lay_co', spawn_type: 'monster', spawn_ref: 'Độc Phong', x: 1100, y: 700, respawn_time: 60 },
  { map_ref: 'dam_lay_co', spawn_type: 'monster', spawn_ref: 'Độc Phong', x: 2000, y: 1300, respawn_time: 60 },
  { map_ref: 'dam_lay_co', spawn_type: 'monster', spawn_ref: 'Độc Xà', x: 400, y: 1200, respawn_time: 35 },
  // Hang Vạn Độc
  { map_ref: 'hang_van_doc', spawn_type: 'boss', spawn_ref: 'Vạn Độc Cổ Vương', x: 900, y: 600, respawn_time: 600 },
  { map_ref: 'hang_van_doc', spawn_type: 'npc', spawn_ref: 'Vạn Độc Cổ Vương', x: 900, y: 600, respawn_time: 30 },
  { map_ref: 'hang_van_doc', spawn_type: 'monster', spawn_ref: 'Độc Phong', x: 400, y: 400, respawn_time: 60 },
  { map_ref: 'hang_van_doc', spawn_type: 'monster', spawn_ref: 'Độc Chu', x: 1400, y: 800, respawn_time: 40 },
  { map_ref: 'hang_van_doc', spawn_type: 'monster', spawn_ref: 'Độc Xà', x: 500, y: 1000, respawn_time: 35 },
];

export const namCuongDialogueSeeds = [
  // Lão Độc Sư — intro
  {
    ref: 'dlg_lao_doc_su_intro_1',
    npc_ref: 'Lão Độc Sư',
    order_index: 0,
    text: 'Khách từ phương Bắc tới? Hiếm có lắm... Ta là Độc Phong, trưởng lão Vạn Độc Môn nơi đây. Ngươi đã vượt qua cổng gió băng đến đây, chắc chắn không phải kẻ bình thường.',
    speaker: 'Lão Độc Sư',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_lao_doc_su_intro_2' }]),
  },
  {
    ref: 'dlg_lao_doc_su_intro_2',
    npc_ref: 'Lão Độc Sư',
    order_index: 1,
    text: 'Nam Cương này là vùng đất nguyên sinh khắc nghiệt nhất. Độc khí lan tràn khắp nơi, quái thú nguy hiểm. Nếu ngươi muốn tồn tại, hãy học cách chế ngự độc khí trước khi tiến sâu vào Rừng Độc.',
    speaker: 'Lão Độc Sư',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_lao_doc_su_intro_3' }]),
  },
  {
    ref: 'dlg_lao_doc_su_intro_3',
    npc_ref: 'Lão Độc Sư',
    order_index: 2,
    text: 'Rừng Độc phía Đông đang bị bầy Độc Xà và Độc Chu làm loạn. Trước tiên hãy tiêu diệt chúng để chứng tỏ ta. Sau đó ta sẽ chỉ ngươi con đường vào Đầm Lầy Cổ, nơi có Cổ Trùng Hoang Dã nguy hiểm hơn nhiều.',
    speaker: 'Lão Độc Sư',
    choices: JSON.stringify([
      { text: 'Ta sẵn sàng!', next_dialogue_ref: 'dlg_lao_doc_su_accept' },
      { text: 'Vạn Độc Cổ Vương là ai?', next_dialogue_ref: 'dlg_lao_doc_su_boss_info' },
    ]),
  },
  {
    ref: 'dlg_lao_doc_su_boss_info',
    npc_ref: 'Lão Độc Sư',
    order_index: 3,
    text: 'Vạn Độc Cổ Vương... là sinh vật cổ đại thất thường ngàn năm ẩn cư trong Hang Vạn Độc. Toàn thân nó tụ tập vạn loại độc, ngay cả Tiên Cảnh đột nhập cũng phải kiêng dè. Chưa bao giờ có tu sĩ Ba Chuyển nào trở về từ hang đó.',
    speaker: 'Lão Độc Sư',
    choices: JSON.stringify([{ text: 'Ta sẽ là người đầu tiên!', next_dialogue_ref: 'dlg_lao_doc_su_accept' }]),
  },
  {
    ref: 'dlg_lao_doc_su_accept',
    npc_ref: 'Lão Độc Sư',
    order_index: 4,
    text: 'Can đảm lắm! Trước khi đi, hãy đến Thương Nhân Độc Vật mua thêm Luyện Cổ Đan. Đó là vật phẩm đặc trưng Nam Cương. Chúc ngươi thắng lợi!',
    speaker: 'Lão Độc Sư',
    set_flag: 'ch2_intro_done',
  },
  {
    ref: 'dlg_lao_doc_su_after_hunt',
    npc_ref: 'Lão Độc Sư',
    order_index: 5,
    text: 'Xuất sắc! Rừng Độc giờ an toàn hơn rồi. Bây giờ tiến sâu vào Đầm Lầy Cổ phía Nam. Ở đó có Cổ Trùng Hoang Dã chứa Cổ Hoang Tinh — thứ ngươi cần để đủ sức đối đầu Vạn Độc Cổ Vương.',
    speaker: 'Lão Độc Sư',
    condition_flag: 'ch2_poison_hunted',
    choices: JSON.stringify([{ text: 'Tiếp tục', next_dialogue_ref: 'dlg_lao_doc_su_after_hunt_2' }]),
  },
  {
    ref: 'dlg_lao_doc_su_after_hunt_2',
    npc_ref: 'Lão Độc Sư',
    order_index: 6,
    text: 'Cổ Hoang Tinh là tinh hoa của Cổ Trùng hoang dã, mang trong mình khí tức Cổ Đạo nguyên sơ. Sau khi thu thập đủ, hãy tiến vào Hang Vạn Độc mà đối mặt với quân chủ của vùng đất này!',
    speaker: 'Lão Độc Sư',
    set_flag: 'ch2_sent_to_boss',
  },
  // Merchant dialogue
  {
    ref: 'dlg_merchant_doc_vat',
    npc_ref: 'Thương Nhân Độc Vật',
    order_index: 0,
    text: 'Chào tu sĩ! Nam Cương có những đặc sản không đâu có. Luyện Cổ Đan của ta chế từ Độc Thảo nguyên chất, giúp Cổ Trùng của ngươi hấp thụ độc khí đặc biệt tốt. Có mua không?',
    speaker: 'Thương Nhân Độc Vật',
  },
  // Wanderer hint dialogue
  {
    ref: 'dlg_kiem_su_tan_tu_1',
    npc_ref: 'Kiếm Sư Tán Tu',
    order_index: 0,
    text: 'Này tu sĩ, ta là tán tu lang bạt khắp thiên hạ. Nam Cương cực kỳ nguy hiểm, nhưng cũng là nơi Cổ Trùng hệ Độc mạnh nhất thiên hạ xuất hiện. Nếu có thể thuần phục được chúng, ngươi sẽ trở nên vô địch trong PvP.',
    speaker: 'Kiếm Sư Tán Tu',
    choices: JSON.stringify([{ text: 'Cảm ơn tin tức!', next_dialogue_ref: 'dlg_kiem_su_tan_tu_2' }]),
  },
  {
    ref: 'dlg_kiem_su_tan_tu_2',
    npc_ref: 'Kiếm Sư Tán Tu',
    order_index: 1,
    text: 'Một lời khuyên: vào Hang Vạn Độc thì đừng dùng hệ Hỏa — Vạn Độc Cổ Vương miễn nhiễm hoàn toàn. Hệ Phong và Lôi là hai hệ gây sát thương nhiều nhất với nó. Chúc may mắn!',
    speaker: 'Kiếm Sư Tán Tu',
  },
  // Boss confrontation
  {
    ref: 'dlg_boss_ch2_confront_1',
    npc_ref: 'Vạn Độc Cổ Vương',
    order_index: 0,
    text: 'Sssss... Kẻ bé nhỏ kia, ngươi dám xâm nhập lãnh địa của ta? Mười ngàn năm rồi không có ai đến đây... Ta sẽ dùng ngươi làm thức ăn để bổ sung độc khí!',
    speaker: 'Vạn Độc Cổ Vương',
    choices: JSON.stringify([{ text: 'Ta đến đây để chiến!', next_dialogue_ref: 'dlg_boss_ch2_confront_2' }]),
  },
  {
    ref: 'dlg_boss_ch2_confront_2',
    npc_ref: 'Vạn Độc Cổ Vương',
    order_index: 1,
    text: 'Hahaha! Ngươi mang trong người hơi thở của Cổ Đạo... Sinh Cổ! Thú vị lắm. Chính xác vì vậy ta mới muốn nuốt trọn ngươi để hấp thu Cổ Đạo nguyên khí. Hãy đến đây cho ta thưởng thức!!!',
    speaker: 'Vạn Độc Cổ Vương',
    set_flag: 'ch2_boss_confronted',
  },
];

export const chapter2QuestSeeds = [
  {
    ref: 'q_ch2_arrive',
    name: 'Độc Địa Nam Phương',
    type: 'main',
    description: 'Vượt qua cổng gió đến vùng đất Nam Cương đầy độc khí. Hãy tìm gặp Lão Độc Sư để hiểu rõ tình hình.',
    npc_giver_ref: 'Lão Độc Sư',
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch1_complete' },
    ]),
    objectives: JSON.stringify([
      { type: 'talk', target: 'Lão Độc Sư', count: 1, description: 'Nói chuyện với Lão Độc Sư ở Trấn Độc Trì' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 200 },
      { type: 'exp', amount: 100 },
      { type: 'item', item_ref: 'Luyện Cổ Đan', amount: 3 },
    ]),
    flag_required: 'ch1_complete',
    flag_complete: 'ch2_arrived',
    min_realm: 2,
  },
  {
    ref: 'q_ch2_poison_hunt',
    name: 'Trừ Độc Rừng Tà',
    type: 'main',
    description: 'Bầy Độc Xà và Độc Chu đang quấy nhiễu Rừng Độc, gây nguy hiểm cho người dân Trấn Độc Trì. Tiêu diệt chúng để chứng minh tu vi.',
    npc_giver_ref: 'Lão Độc Sư',
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch2_arrived' },
    ]),
    objectives: JSON.stringify([
      { type: 'kill', target: 'Độc Xà', count: 3, description: 'Tiêu diệt 3 Độc Xà trong Rừng Độc' },
      { type: 'kill', target: 'Độc Chu', count: 2, description: 'Tiêu diệt 2 Độc Chu trong Rừng Độc' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 300 },
      { type: 'exp', amount: 150 },
      { type: 'item', item_ref: 'Nọc Độc', amount: 5 },
    ]),
    flag_required: 'ch2_arrived',
    flag_complete: 'ch2_poison_hunted',
    min_realm: 2,
  },
  {
    ref: 'q_ch2_essence',
    name: 'Cổ Hoang Tinh',
    type: 'main',
    description: 'Lão Độc Sư cần Cổ Hoang Tinh từ Cổ Trùng Hoang Dã trong Đầm Lầy Cổ để chuẩn bị cho cuộc đối đầu cuối cùng. Hãy thu thập nó.',
    npc_giver_ref: 'Lão Độc Sư',
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch2_poison_hunted' },
    ]),
    objectives: JSON.stringify([
      { type: 'kill', target: 'Cổ Trùng Hoang Dã', count: 1, description: 'Đánh bại Cổ Trùng Hoang Dã để lấy Cổ Hoang Tinh' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 400 },
      { type: 'exp', amount: 200 },
      { type: 'item', item_ref: 'Cổ Hoang Tinh', amount: 1 },
    ]),
    flag_required: 'ch2_poison_hunted',
    flag_complete: 'ch2_essence_collected',
    min_realm: 3,
  },
  {
    ref: 'q_ch2_boss',
    name: 'Vạn Độc Cổ Vương',
    type: 'main',
    description: 'Với Cổ Hoang Tinh trong tay, ngươi đã sẵn sàng đối mặt với Vạn Độc Cổ Vương trong Hang Vạn Độc. Đây là thử thách quyết định đột phá Tam Chuyển.',
    npc_giver_ref: null,
    prerequisites: JSON.stringify([
      { type: 'flag', key: 'ch2_essence_collected' },
    ]),
    objectives: JSON.stringify([
      { type: 'kill', target: 'Vạn Độc Cổ Vương', count: 1, description: 'Đánh bại Vạn Độc Cổ Vương trong Hang Vạn Độc' },
    ]),
    rewards: JSON.stringify([
      { type: 'gold', amount: 1000 },
      { type: 'exp', amount: 500 },
      { type: 'item', item_ref: 'Cổ Hoang Tinh', amount: 3 },
      { type: 'spirit_stone', amount: 20 },
    ]),
    flag_required: 'ch2_essence_collected',
    flag_complete: 'ch2_complete',
    min_realm: 3,
  },
];
